# render.yaml
services:
  - type: web
    name: device-rx
    env: node
    plan: free # can be changed to a paid plan
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: GOOGLE_API_KEY
        value: "" # Set this in your Render environment variables